version: '0.1'
services:
  scim:
    build: .
    ports: 
      - 8888:8888
    volumes:
      - /home/igupta/computeenv/scim/workdir:/workdir
      - /mnt/d/projects/scim/data:/data
      - /mnt/d/projects/scim/dependencies:/dependencies
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
